language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=/opt/devkitpro    
    - WUT_ROOT=/opt/devkitpro/wut
    - DEVKITPPC=/opt/devkitpro/devkitPPC
    - PORTLIBREPOS=$HOME/portlibrepos

cache:
  directories:
    - "$HOME/.local"
    - "$DEVKITPRO"

addons:
  apt:
    packages:
    - p7zip-full
    
before_install:
  - mkdir -p "${PORTLIBREPOS}"
  - mkdir -p "${DEVKITPRO}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb; fi
  - yes | sudo dkp-pacman -Syu devkitPPC --needed
  - yes | sudo dkp-pacman -Syu general-tools --needed
  - wget $(curl -s https://api.github.com/repos/decaf-emu/wut/releases/latest | grep 'browser_' | grep 'linux' | cut -d\" -f4)

install:  
  - 7z x -y $(ls | grep "linux") -o${WUT_ROOT}
  - cd $PORTLIBREPOS
  - git clone https://github.com/Maschell/WiiUPluginSystem.git
  - git clone https://github.com/Maschell/controller_patcher_configs.git
  - git clone https://github.com/Maschell/libutils.git -b wut
  - git clone https://github.com/Maschell/controller_patcher.git -b wut
  - cd WiiUPluginSystem
  - make && make install
  - cd $PORTLIBREPOS  
  - cd libutils
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/share/wut.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$WUT_ROOT ../
  - make install
  - cd $PORTLIBREPOS
  - cd controller_patcher
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$WUT_ROOT/share/wut.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$WUT_ROOT ../
  - make install

before_script:
  - cd $TRAVIS_BUILD_DIR/

script:
- make -j8

before_deploy:
- mkdir -p "wiiu/plugins"
- mkdir -p "wiiu/controller"
- cp $PORTLIBREPOS/controller_patcher_configs/*.ini ./wiiu/controller
- commit="$(git rev-parse --short=7 HEAD)"
- cp hidtovpad.mod wiiu/plugins/
- versiontag="$(./gitrev.sh)"
- zip -r hid_to_vpad_$versiontag.zip wiiu
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=HIDtoVPAD-WUPS-$versiontag
- commitLog="$(git log -1 --pretty=%B)"
- commitMessage="$(echo -e "-\n" && echo "HID to VPAD nightly WUPS build. Not a stable release. Expect bugs!" && echo -e "Commitlog:")"
- git tag $GIT_TAG -a -m "$commitMessage" -m "$commitLog"
- git push --quiet https://$GITHUBKEY@github.com/Maschell/hid_to_vpad $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
    secure: "r2jF3dwTUdeo+0Rg5cDuJhxJU3kVnsEbCfIxRrL0QLjPQUCIPLQyqZCC2ApBW1VrOZ7oH6HUW1RhXdnu2izN2Bsis5jPmCJl4vDDb6tWvdW/h2BbZOiOqsGkjTVxBYs6ZddnENxrJBUBHyDbPijERr8lVMhs066S0yPQvVGWG9K+ClXkS2bO/Mq3wO/CzQNv93LrZXWGgkB9Ej2bzcYrt+ieA3jkVOn9K3PbLapRQCNec4RM3R+dJT4uQmrih892e4+JzZlyf4HGmIFH8xNIPQvXH5wD1nGcTzXDC6eQw5ljMPaxhWn2YtIv9knUKjhWzEe9fx8e+380SjpTTP0ir6I+EF2Y/A5spYJMuJDHLSvU2Qq1BwfE4pm/Om+/wRlTaPC8FYUuQPc1YdBLRYBpd3YwlJFEZSi4IEUbEOjOKDhagw0cYHQC42zypsm1aW+q8eVSeylsyjxOR2eawVHIzvOoMKA0FHIdA7zNFxh50y3EdYJw+L6/4wU14743ifT5TOrMuTWfSQXY4eBBkjMytkkhMsJfbs2xHHZkBgl2249Z93odr+2C5WbOqnEQRhPZunOxrMO8bga/K50wmTfOPSxkFJOxXnOuXlGWd0TsUeAtGg7Nk3pRaPVXhOMc+gXb/Ktdj6S11bUNO4VLXb4z7FmMy0yxmxrw3elpXDjaB/U="
  file: hid_to_vpad_WUPS_$versiontag.zip
  on:
    repo: Maschell/hid_to_vpad
    tags: false
    all_branches: true